/*
** The executor will take the command table generated by the parser and for every
** SimpleCommand in the array it will create a new process. It will also if
** necessary create pipes to communicate the output of one process to the input
** of the next one. Additionally, it will redirect the standard input,
** standard output, and standard error if there are any redirections.
*/

#include "../includes/minishell.h"
